server:
  port: 8080

missing-field-config:
  schemas:
    CreateShipment:
      required:
        - sender_name
        - sender_address
        - sender_phone
        - receiver_name
        - receiver_address
        - receiver_phone
        - package_weight
        - package_description
        - delivery_type
      optional:
        - pickup_required
        - pickup_address
      conditional:
        pickup_address: "pickup_required:true"
    TrackShipment:
      required:
        - tracking_number
    ReturnShipment:
      required:
        - tracking_number
        - reason
      optional:
        - pickup_address
    RescheduleDelivery:
      required:
        - tracking_number
        - new_delivery_time
    ReportIssue:
      required:
        - tracking_number
        - issue_type
        - description
      optional:
        - photo_url

  synonyms:
    recipient: receiver_name
    reciever_name: receiver_name
    phone: sender_phone
    mobile: sender_phone
    delivery: delivery_type
    status: delivery_status
    reschedule: new_delivery_time

  prompts:
    sender_name: "What is the sender's name?"
    sender_address: "What is the sender's address?"
    sender_phone: "Sender's phone number?"
    receiver_name: "Who is the receiver?"
    receiver_address: "What is the receiver's address?"
    receiver_phone: "Receiver's phone number?"
    package_weight: "How much does the package weigh (in kg)?"
    package_description: "What are you sending?"
    delivery_type: "Is this standard or express delivery?"
    pickup_required: "Do you need a pickup? (yes/no)"
    pickup_address: "If pickup required, provide pickup address."
    tracking_number: "What is your tracking number?"
    reason: "Why do you want to return the shipment?"
    new_delivery_time: "What date and time do you want to reschedule to?"
    issue_type: "Is your package lost or damaged?"
    description: "Please describe the issue."
    photo_url: "Upload a photo of the package (optional)."

  validations:
    sender_phone: "phone"
    receiver_phone: "phone"
    package_weight: "positive_number"
    delivery_type: "enum:standard,express"
    pickup_required: "boolean"
    tracking_number: "alphanumeric"
    new_delivery_time: "datetime"
    issue_type: "enum:lost,damaged"
    photo_url: "url"
    reason: "non_empty"